substitutions:
  _REGION: us-central1
  _GEMINI_CALLER_SA: ""
  _SERVICE_URL: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - a2a/Dockerfile.a2a
      - -t
      - gcr.io/$PROJECT_ID/agentbox-a2a:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/agentbox-a2a:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        sed \
          -e "s|gcr.io/PROJECT_ID/agentbox-a2a:latest|gcr.io/$PROJECT_ID/agentbox-a2a:$COMMIT_SHA|g" \
          -e "s|PROJECT_ID|$PROJECT_ID|g" \
          -e "s|GEMINI_CALLER_SA_PLACEHOLDER|${_GEMINI_CALLER_SA}|g" \
          -e "s|SERVICE_URL_PLACEHOLDER|${_SERVICE_URL}|g" \
          a2a/cloud_run/service.yaml | \
        gcloud run services replace - \
          --region ${_REGION} \
          --platform managed
        gcloud run services remove-iam-policy-binding agentbox-a2a \
          --region ${_REGION} \
          --member="allUsers" \
          --role="roles/run.invoker" 2>/dev/null || true

images:
  - gcr.io/$PROJECT_ID/agentbox-a2a:$COMMIT_SHA
